import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Layout pageTitle='Home Page'>
      <Image src="/profile.png" width={200} height={200} alt='profile'/>
      <h1 className={styles['title-homepage']}>Welcome Umi</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <Image src="/post1.png" width={200} height={200} alt='post1'/>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, dolorum illo molestias, ducimus labore perspiciatis eum explicabo ab est quidem voluptatem rem corporis quaerat exercitationem facilis accusamus perferendis voluptatum obcaecati!</p>
      <Image src="/post2.png" width={200} height={200} alt='post2'/>
    </Layout>
  )
}
